{% set version = "13.0.0" %}

package:
  name: av
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: 7fb1a5588cd8ce4d0564ddf82221f886541ea2d5152f15e63ab890430dcd3c31
  patches:
    - patches/lgpl_tests.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - cython
    - numpy
    - ffmpeg  {{ ffmpeg }}=lgpl*
  run:
    - python
    - pillow
    - numpy >=1.22

test:
  requires:
    # The compiled pyav should be compatibile with both the GPL version of
    # ffpmpeg and the lgpl version of ffmpeg
    - ffmpeg *=gpl*    # [py==311]
    - ffmpeg *=lgpl*   # [py==312]
  commands:
    # With the GPL version, x264 and x265 should be available
    - python -c "import av; assert 'libx264' in av.codecs_available"       # [py==311]
    - python -c "import av; assert 'libx265' in av.codecs_available"       # [py==311]
    # But they won't be available if the user chooses the lgpl version
    - python -c "import av; assert 'libx264' not in av.codecs_available"   # [py==312]
    - python -c "import av; assert 'libx265' not in av.codecs_available"   # [py==312]
    # openh264 should always be available from conda-forge
    - python -c "import av; assert 'libopenh264' in av.codecs_available"
  imports:
    - av
    - av.audio
    - av.audio.fifo

about:
  home: https://github.com/PyAV-Org/PyAV/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic bindings for FFmpeg.

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk
