{% set version = "9.2.0" %}

package:
  name: av
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: f2a7c226724d7f7745b376b459c500d9d17bd8d0473b7ea6bf8ddb4f7957c69d

build:
  number: 2
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    # 2022/02/06: hmaarrfk
    # Tests don't seem to be passing on azure with ppc64le
    - python setup.py test                   # [(build_platform == target_platform) and (not ppc64le)]
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - cython
    - numpy
    - ffmpeg  {{ ffmpeg }}=lgpl*
    - pillow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow

test:
  requires:
    # The compiled pyav should be compatibile with both the GPL version of
    # ffpmpeg and the lgpl version of ffmpeg
    - ffmpeg *=gpl*    # [py==39]
    - ffmpeg *=lgpl*   # [py==310]
  commands:
    # With the GPL version, x264 and x265 should be available
    - python -c "import av; assert 'libx264' in av.codecs_available"       # [py==39]
    - python -c "import av; assert 'libx265' in av.codecs_available"       # [py==39]
    # But they won't be available if the user chooses the lgpl version
    - python -c "import av; assert 'libx264' not in av.codecs_available"   # [py==310]
    - python -c "import av; assert 'libx265' not in av.codecs_available"   # [py==310]
    # openh264 should always be available from conda-forge
    - python -c "import av; assert 'libopenh264' in av.codecs_available"
  imports:
    - av
    - av.audio
    - av.audio.fifo

about:
  home: https://github.com/PyAV-Org/PyAV/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic bindings for FFmpeg.

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk
