{% set version = "15.0.0" %}

package:
  name: av
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: 871c1a9becddf00b60b1294dc0bff9ff193ac31286aeec1a34039bd27e650183
  patches:
    - patches/lgpl_tests.patch
    - patches/remove_checks_in_setup.patch

    # Backported to get up to ffmpeg8 compatibility
    # https://github.com/PyAV-Org/PyAV/pull/1988
    # - patches/0001-Remove-checks-in-setup.py.patch
    # - patches/0002-Avoid-setting-channel-variable.patch
    # - patches/0003-Remove-attachment-docs.patch
    # - patches/0004-Use-AVPacket.time_base.patch
    # - patches/0005-Install-cython-from-scientific-python-nightlies-in-s.patch
    # - patches/0006-Add-set_image-for-updating-the-image-content-of-an-e.patch
    # - patches/0007-Index-opaque-by-id-and-make-key_frame-writable.patch
    # - patches/0008-Fix-opaque-container-on-PyPy.patch
    - patches/0009-Replace-FFmpeg-version-macro-with-direct-API-call.patch
    - patches/0010-Combine-pad-and-link.patch
    - patches/0011-Remove-FilterFlags.patch
      # - patches/0012-Remove-unused-swr-functions.patch
    - patches/0013-Build-with-ffmpeg-8.patch

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - ffmpeg  {{ ffmpeg }}=lgpl*
  run:
    - python
    - pillow
    - numpy >=1.22

{% set tests_to_skip = "_not_a_real_test" %}
# hmaarrfk - 2024/09
# Seems like this test fails with ppc64le when using emulation (not tested natively)
{% set tests_to_skip = tests_to_skip + " or test_generator_graph" %}              # [ppc64le]
{% set tests_to_skip = tests_to_skip + " or test_reformat_pixel_format_align" %}  # [ppc64le]

# Seems like this test fails with aarch... but only with the gpl variant... i can't
# figure it out .... hmaarrffk 2025/03
{% set tests_to_skip = tests_to_skip + " or test_generator_graph" %}              # [aarch64]

test:
  source_files:
    - tests
  requires:
    # The compiled pyav should be compatibile with both the GPL version of
    # ffpmpeg and the lgpl version of ffmpeg
    - ffmpeg *=gpl*    # [py==311]
    - ffmpeg *=lgpl*   # [py==312]
    - pytest
  commands:
    # With the GPL version, x264 and x265 should be available
    - python -c "import av; assert 'libx264' in av.codecs_available"       # [py==311]
    - python -c "import av; assert 'libx265' in av.codecs_available"       # [py==311]
    # But they won't be available if the user chooses the lgpl version
    - python -c "import av; assert 'libx264' not in av.codecs_available"   # [py==312]
    - python -c "import av; assert 'libx265' not in av.codecs_available"   # [py==312]
    # openh264 should always be available from conda-forge
    - python -c "import av; assert 'libopenh264' in av.codecs_available"
    # Follow thei rtest commands from
    # https://github.com/PyAV-Org/PyAV/blob/main/.github/workflows/tests.yml#L72
    - pytest tests -k "not ({{ tests_to_skip }})"
  imports:
    - av
    - av.audio
    - av.audio.fifo

about:
  home: https://github.com/PyAV-Org/PyAV/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic bindings for FFmpeg.

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk
