{% set version = "16.1.0" %}

package:
  name: av
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/av/av-{{ version }}.tar.gz
  sha256: a094b4fd87a3721dacf02794d3d2c82b8d712c85b9534437e82a8a978c175ffd
  patches:
    - patches/0001-Convert-h264-tests-to-openh264-for-lgpl-build.patch
    - patches/0002-Disable-cp111-abi.patch
    - patches/cleanup_more_pylimited.patch

build:
  number: 0
  # https://github.com/PyAV-Org/PyAV/blob/main/pyproject.toml#L13
  skip: true  # [py<311]
  script:
    - {{ PYTHON }} -m pip install . -vv
  run_exports:
    # PyAV now claims to follow semantic versioning
    - {{ pin_subpackage('av') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - ffmpeg {{ ffmpeg }} lgpl*
  run:
    - python
    - pillow
    - numpy >=1.22

{% set tests_to_skip = "_not_a_real_test" %}
# hmaarrfk - 2024/09
# Seems like this test fails with ppc64le when using emulation (not tested natively)
{% set tests_to_skip = tests_to_skip + " or test_generator_graph" %}              # [ppc64le]
{% set tests_to_skip = tests_to_skip + " or test_reformat_pixel_format_align" %}  # [ppc64le]

# Seems like this test fails with aarch... but only with the gpl variant... i can't
# figure it out .... hmaarrffk 2025/03
{% set tests_to_skip = tests_to_skip + " or test_generator_graph" %}              # [aarch64]

test:
  source_files:
    - tests
  requires:
    # The compiled pyav should be compatibile with both the GPL version of
    # ffpmpeg and the lgpl version of ffmpeg
    - ffmpeg * gpl*    # [py==311]
    - ffmpeg * lgpl*   # [py==312]
    - pytest
  commands:
    # With the GPL version, x264 and x265 should be available
    - python -c "import av; assert 'libx264' in av.codecs_available"       # [py==311]
    - python -c "import av; assert 'libx265' in av.codecs_available"       # [py==311]
    # But they won't be available if the user chooses the lgpl version
    - python -c "import av; assert 'libx264' not in av.codecs_available"   # [py==312]
    - python -c "import av; assert 'libx265' not in av.codecs_available"   # [py==312]
    # openh264 should always be available from conda-forge
    - python -c "import av; assert 'libopenh264' in av.codecs_available"
    # Follow thei rtest commands from
    # https://github.com/PyAV-Org/PyAV/blob/main/.github/workflows/tests.yml#L72
    - pytest tests -k "not ({{ tests_to_skip }})"
  imports:
    - av
    - av.audio
    - av.audio.fifo

about:
  home: https://github.com/PyAV-Org/PyAV/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic bindings for FFmpeg.

  description: |
    PyAV is a Pythonic binding for FFmpeg or Libav. We aim to provide all of
    the power and control of the underlying library, but manage the gritty
    details as much as possible.
  doc_url: https://pyav.org/docs/develop/
  dev_url: https://github.com/PyAV-Org/PyAV/

extra:
  recipe-maintainers:
    - danielballan
    - mikeboers
    - sdvillal
    - h-vetinari
    - hmaarrfk
